/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MySchool;

import com.sun.glass.events.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SANTOSH
 */
public class StaffDetail extends javax.swing.JFrame {
        
        PreparedStatement pstmt;
        ResultSet rs;
        static File file;
   
    
    /**
     * Creates new form FeeDetail
     */
    public StaffDetail() {        
        pstmt=null;
        rs=null;        
        file=null;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();            
        this.setLocationRelativeTo(null);
        Calendar calendar = Calendar.getInstance();
   
     
        YearChooser.setEndYear(calendar.get(Calendar.YEAR)); //will set current year as end year
        YearChooser.setValue(calendar.get(Calendar.YEAR));  //will set only value to be visibled
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        resigndateLabel = new javax.swing.JLabel();
        joindateLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        totLabel1 = new javax.swing.JLabel();
        totLabel2 = new javax.swing.JLabel();
        YearChooser = new com.toedter.calendar.JYearChooser();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        refreshLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        msgLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        fnameTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        mobnoTextField = new javax.swing.JTextField();
        hphoneTextField = new javax.swing.JTextField();
        qualificationTextField = new javax.swing.JTextField();
        tenthTextField = new javax.swing.JTextField();
        twelthTextField = new javax.swing.JTextField();
        ugTextField = new javax.swing.JTextField();
        pgTextField = new javax.swing.JTextField();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        joinDateChooser = new com.toedter.calendar.JDateChooser();
        resignDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        addTextArea = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        descComboBox = new javax.swing.JComboBox<>();
        dobTextField = new javax.swing.JTextField();
        joinTextField = new javax.swing.JTextField();
        resignTextField = new javax.swing.JTextField();
        descTextField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        qualificationComboBox = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        Table.setBackground(new java.awt.Color(0, 0, 102));
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "FATHER'S NAME", "ADDRESS", "JOIN_DATE", "RESIGN_DATE"
            }
        ));
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(Table);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setText("Upload Image");
        imgLabel.setBorder(new javax.swing.border.MatteBorder(null));
        imgLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLabelMouseClicked(evt);
            }
        });
        jPanel1.add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 150));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resigndateLabel.setBackground(new java.awt.Color(0, 51, 204));
        resigndateLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        resigndateLabel.setForeground(new java.awt.Color(255, 255, 255));
        resigndateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resigndateLabel.setText("Order By Resigning Date");
        resigndateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resigndateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resigndateLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resigndateLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resigndateLabelMouseExited(evt);
            }
        });
        jPanel2.add(resigndateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        joindateLabel.setBackground(new java.awt.Color(0, 51, 204));
        joindateLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        joindateLabel.setForeground(new java.awt.Color(255, 255, 255));
        joindateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joindateLabel.setText("Order By Joining Date");
        joindateLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        joindateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        joindateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joindateLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                joindateLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                joindateLabelMouseExited(evt);
            }
        });
        jPanel2.add(joindateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, -1));

        nameLabel.setBackground(new java.awt.Color(0, 51, 204));
        nameLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Order By Name");
        nameLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameLabelMouseExited(evt);
            }
        });
        jPanel2.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        totLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        totLabel1.setForeground(new java.awt.Color(255, 255, 255));
        totLabel1.setText("Total :");
        totLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(totLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        totLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        totLabel2.setForeground(new java.awt.Color(255, 255, 255));
        totLabel2.setText("0");
        jPanel2.add(totLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, -1));

        YearChooser.setBackground(new java.awt.Color(0, 0, 102));
        YearChooser.setStartYear(2011);
        YearChooser.setValue(2011);
        jPanel2.add(YearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 30));

        okButton.setBackground(new java.awt.Color(0, 51, 204));
        okButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        okButton.setForeground(new java.awt.Color(255, 255, 255));
        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });
        jPanel2.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Year to See Detail");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1346, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("STAFF DETAIL");

        backLabel.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("<< BACK");
        backLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Log Out");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        refreshLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        refreshLabel.setForeground(new java.awt.Color(255, 255, 255));
        refreshLabel.setText("Refresh");
        refreshLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(backLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(logoutLabel)
                .addGap(54, 54, 54)
                .addComponent(refreshLabel)
                .addGap(71, 71, 71))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutLabel)
                            .addComponent(refreshLabel))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        msgLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 255, 255));
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Father's Name");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DOB");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mobile No.");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home Phone");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Qualification");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("10 th %");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("12 th %");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("UG %");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PG %");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Joining Date");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Resiging Date");

        idTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextFieldKeyReleased(evt);
            }
        });

        nameTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyTyped(evt);
            }
        });

        fnameTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        fnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameTextFieldKeyTyped(evt);
            }
        });

        genderTextField.setEditable(false);
        genderTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        mobnoTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        mobnoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobnoTextFieldKeyTyped(evt);
            }
        });

        hphoneTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        hphoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hphoneTextFieldKeyTyped(evt);
            }
        });

        qualificationTextField.setEditable(false);
        qualificationTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        tenthTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        tenthTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tenthTextFieldKeyTyped(evt);
            }
        });

        twelthTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        twelthTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                twelthTextFieldKeyTyped(evt);
            }
        });

        ugTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ugTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ugTextFieldKeyTyped(evt);
            }
        });

        pgTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        pgTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pgTextFieldKeyTyped(evt);
            }
        });

        dobDateChooser.setDateFormatString("d MMM, yyyy");

        joinDateChooser.setAutoscrolls(true);
        joinDateChooser.setDateFormatString("d MMM, yyyy");

        resignDateChooser.setAutoscrolls(true);
        resignDateChooser.setDateFormatString("d MMM, yyyy");

        addTextArea.setColumns(20);
        addTextArea.setLineWrap(true);
        addTextArea.setRows(5);
        jScrollPane1.setViewportView(addTextArea);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Desc");

        descComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "AD", "HOD", "Director", "Teacher" }));
        descComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        dobTextField.setEditable(false);
        dobTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        joinTextField.setEditable(false);
        joinTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        resignTextField.setEditable(false);
        resignTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        descTextField.setEditable(false);
        descTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "Male", "Female", "Other" }));

        qualificationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "Tenth", "Twelth", "UG", "PG" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(90, 90, 90)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(75, 75, 75)
                        .addComponent(dobTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(56, 56, 56)
                        .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addComponent(mobnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(21, 21, 21)
                        .addComponent(hphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addGap(14, 14, 14)
                        .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pgTextField)
                            .addComponent(ugTextField)
                            .addComponent(twelthTextField)
                            .addComponent(tenthTextField)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(qualificationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(qualificationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(joinTextField)
                                    .addComponent(resignTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resignDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(joinDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(mobnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(hphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(qualificationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qualificationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(tenthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(twelthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(ugTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(pgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(joinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(resignTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resignDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(descComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertButton.setBackground(new java.awt.Color(0, 51, 204));
        insertButton.setForeground(new java.awt.Color(255, 255, 255));
        insertButton.setText("Insert Detail");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        jPanel7.add(insertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        modifyButton.setBackground(new java.awt.Color(0, 51, 204));
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Modify Detail");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });
        jPanel7.add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, -1));

        deleteButton.setBackground(new java.awt.Color(0, 51, 204));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete Detail");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel7.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
              
    /***************************************************************************************/    
    private int myUpdate(String cname,String cvalue,String id){
        int i=0;
        try{            
            pstmt=MyLogin.con.prepareStatement("update STAFF_DETAIL_TABLE set "+cname+" = '"+cvalue+"' where ID = '"+id+"'");            
            i=pstmt.executeUpdate();
            pstmt.clearParameters();
            
            System.out.println("i= "+i);            
            if(i>0){    
                System.out.println("Updated "+cname);
                return i;                
            }                
        }catch(Exception e){ }
        return i;
    }
    
    /*************************************************************************************/
    private void setData(){
        try{
                nameTextField.setText(rs.getString("FULL_NAME"));
                fnameTextField.setText(rs.getString("FATHER_NAME"));
                dobTextField.setText(rs.getString("DOB"));
                genderTextField.setText(rs.getString("GENDER"));
                mobnoTextField.setText(rs.getString("MOB_NO"));
                hphoneTextField.setText(rs.getString("H_PHONE"));
                qualificationTextField.setText(rs.getString("QUALIFICATION"));
                tenthTextField.setText(rs.getString("TENTH"));
                twelthTextField.setText(rs.getString("TWELTH"));
                ugTextField.setText(rs.getString("UG"));
                pgTextField.setText(rs.getString("PG"));
                joinTextField.setText(rs.getString("JOIN_DATE"));
                resignTextField.setText(rs.getString("RESIGN_DATE"));
                descTextField.setText(rs.getString("POSITION"));
                addTextArea.setText(rs.getString("ADDRESS"));    
        }catch(Exception e){ 
        System.out.println("Problem inside setData "+e); }
    }
    
    /*************************************************************************************/
    private void clearFields(){
        nameTextField.setText("");
        fnameTextField.setText("");
        dobTextField.setText("");
        genderTextField.setText("");
        mobnoTextField.setText("");
        hphoneTextField.setText("");
        qualificationTextField.setText("");
        tenthTextField.setText("");
        twelthTextField.setText("");
        ugTextField.setText("");
        pgTextField.setText("");
        joinTextField.setText("");
        resignTextField.setText("");
        descTextField.setText("");
        addTextArea.setText("");
    }
 /*************************************************************************************/
    private void showDetail(String order){              
        int tot=0;
        int yr=0;
        try{            
                rs=null;
                pstmt=MyLogin.con.prepareStatement("select ID,FULL_NAME,FATHER_NAME,ADDRESS,JOIN_DATE,RESIGN_DATE from STAFF_DETAIL_TABLE order by "+order+"");                                     
                rs=pstmt.executeQuery();
                pstmt.clearParameters();                 
           
            DefaultTableModel tm=(DefaultTableModel)Table.getModel(); 
               
        //    for(;tm.getRowCount()>0;tm.removeRow(0));
            while(tm.getRowCount()>0){                    
                    tm.removeRow(0);
                }        
            tot=0;       
            while(rs.next()){
                int flag=0,join_year=0,resign_year=0;
                yr=0;
                String santosh="",resigndate="";
                    
                    yr=YearChooser.getYear();                    
                    santosh=rs.getString("JOIN_DATE");
                    join_year=Integer.parseInt(santosh.substring(7));
                    if(yr>=join_year){       
                        resigndate=rs.getString("RESIGN_DATE");
                        if(resigndate.equalsIgnoreCase("-"))
                            flag=1;
                        else{
                            resign_year=Integer.parseInt(resigndate.substring(7));
                            if(resign_year>=yr)
                                flag=1;
                        }
                    }
                    if(flag==1){
                        tot++;                                                
                        Object kk[]={rs.getString("ID"),rs.getString("FULL_NAME"),rs.getString("FATHER_NAME"),rs.getString("ADDRESS"),rs.getString("JOIN_DATE"),rs.getString("RESIGN_DATE")};
                        tm.addRow(kk);   
                    }
            }
            msgLabel.setText("LIST OF TEACHERS IN THE YEAR : "+yr);
            totLabel2.setText(""+tot);           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Entry (year/date) ", "Detail", JOptionPane.ERROR_MESSAGE);           
        }      
    }
    
    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));    
        showDetail("ID");              
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_okButtonMouseClicked

    private void nameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameLabelMouseClicked
                showDetail("FULL_NAME");
            //    MySpeak.mySpeach("List of teachers in the year "+YearChooser.getYear()+".Order by name");
    }//GEN-LAST:event_nameLabelMouseClicked

    private void joindateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joindateLabelMouseClicked
                showDetail("JOIN_DATE");                    
    }//GEN-LAST:event_joindateLabelMouseClicked

    private void joindateLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joindateLabelMouseEntered
              //  nameLabel.setBackground(new java.awt.Color(0, 51, 204));
        joindateLabel.setOpaque(true);
        joindateLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_joindateLabelMouseEntered

    private void joindateLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joindateLabelMouseExited
             //  nameLabel.setBackground(new java.awt.Color(0, 51, 204));
        joindateLabel.setOpaque(false);
        joindateLabel.setBorder(null);
    }//GEN-LAST:event_joindateLabelMouseExited

    private void nameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameLabelMouseEntered
        // TODO add your handling code here:
        nameLabel.setOpaque(true);
        nameLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_nameLabelMouseEntered

    private void nameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameLabelMouseExited
        // TODO add your handling code here:
        nameLabel.setOpaque(false);
        nameLabel.setBorder(null);
    }//GEN-LAST:event_nameLabelMouseExited

    private void resigndateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resigndateLabelMouseClicked
        showDetail("RESIGN_DATE");            
    }//GEN-LAST:event_resigndateLabelMouseClicked

    private void resigndateLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resigndateLabelMouseEntered
        // TODO add your handling code here:
        resigndateLabel.setOpaque(true);
        resigndateLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_resigndateLabelMouseEntered

    private void resigndateLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resigndateLabelMouseExited
        // TODO add your handling code here:
        resigndateLabel.setOpaque(false);
        resigndateLabel.setBorder(null);
    }//GEN-LAST:event_resigndateLabelMouseExited
      
    private int checkId(){
        int i=0;
        try{
            rs=null;
            pstmt=MyLogin.con.prepareStatement("select ID from STAFF_DETAIL_TABLE where ID = ?");
            pstmt.setString(1, idTextField.getText().trim());
            rs=pstmt.executeQuery();
            if(rs.next()){
                i=1;               
            }
        }catch(Exception e){
            System.out.println("problem inside checkIdMethod "+e);
        }
        return i;
    }
    
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        String id="",name="",fname="", dob="",gender="",mobno="",hphone="",qualification="",tenth="",twelth="",ug="",pg="",join="",resign="",desc="",add="";
        int flag=0;
        DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);	      
        flag = checkId();  //will check duplication
    if(flag!=1){
        try{
            if((ImageIO.read(file)==null)){
                JOptionPane.showMessageDialog(null, "Upload Image", "Insert", JOptionPane.ERROR_MESSAGE); 
            }else{                
            try{
                resign=df.format(resignDateChooser.getDate());
            }catch(Exception e){
                System.out.println(""+e);
                resign="-";
            }
            try{
                dob=df.format(dobDateChooser.getDate());
                join=df.format(joinDateChooser.getDate());
                gender=(String)genderComboBox.getSelectedItem();
                qualification=(String)qualificationComboBox.getSelectedItem();
                desc=(String)descComboBox.getSelectedItem();
                id=idTextField.getText().trim();
                name=nameTextField.getText().trim();
                fname=fnameTextField.getText().trim();
                mobno=mobnoTextField.getText().trim();
                hphone=hphoneTextField.getText().trim();
                tenth=tenthTextField.getText().trim();
                twelth=twelthTextField.getText().trim();
                ug=ugTextField.getText().trim();
                pg=pgTextField.getText().trim();
                add=addTextArea.getText().trim();
                
                pstmt=MyLogin.con.prepareStatement("insert into STAFF_DETAIL_TABLE(ID,FULL_NAME,FATHER_NAME,DOB,GENDER,MOB_NO,H_PHONE,QUALIFICATION,TENTH,TWELTH,UG,PG,JOIN_DATE,RESIGN_DATE,POSITION,ADDRESS) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ");
                if(id.equalsIgnoreCase("")==false)
                    pstmt.setString(1, id);
                
                if(name.equals("")==false)
                    pstmt.setString(2, name);
                
                if(fname.equalsIgnoreCase("")==false)
                    pstmt.setString(3, fname);
                if(dob.length()==11){
                    pstmt.setString(4, dob);
                }
                if((gender.equalsIgnoreCase("---Select---"))==false) {
                    pstmt.setString(5, gender);
                }
                
                if((mobno.equalsIgnoreCase("")||mobno.length()!=10)==false)
                    pstmt.setString(6, mobno);
                
                if((hphone.equalsIgnoreCase("")||hphone.length()!=10)==false)
                    pstmt.setString(7, hphone);
                if((qualification.equalsIgnoreCase("---Select---"))==false){
                    pstmt.setString(8, qualification);
                }
                
                if((tenth.equalsIgnoreCase("")||tenth.length()>5||tenth.length()==1)==false)
                    pstmt.setString(9, tenth);
                if((twelth.length()>5||twelth.length()==1)==false)
                    pstmt.setString(10, twelth);
                if((ug.length()>5||ug.length()==1)==false)
                    pstmt.setString(11, ug);
                if((pg.length()>5||pg.length()==1)==false)
                    pstmt.setString(12, pg);
                if(join.length()==11){
                    pstmt.setString(13, join);
                }
                pstmt.setString(14, resign);       //Because current teacher cannot give resign date
                if((desc.equalsIgnoreCase("---Select---"))==false){
                    pstmt.setString(15, desc);
                }
                if(add.equalsIgnoreCase("")==false){
                    pstmt.setString(16, add);
                }
                                                
                int i=pstmt.executeUpdate();
                pstmt.clearParameters();
                if(i>0){
                    ImageProcessing.saveTeacherImage(id);
                    file=null;
                    JOptionPane.showMessageDialog(null, "One Record Inserted Successfully", "Insert Record", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("Data inserted successfully");
                    //       showDetail();
                }else
                    System.out.println("Sorry data cannot be inserted");
                
            }catch(Exception e){
                System.out.println("Problem inside insert button "+e);
                JOptionPane.showMessageDialog(null, "Fill all Details carefully", "Adding Detail", JOptionPane.ERROR_MESSAGE);
            }
          }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Upload Image", "Upload", JOptionPane.ERROR_MESSAGE);
            System.out.println("Please Upload image "+e);
        }
    }else{
        JOptionPane.showMessageDialog(null, "Already Registered with Id "+idTextField.getText(), "Insert Record",JOptionPane.ERROR_MESSAGE);
    }
    insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_insertButtonActionPerformed

    private void idTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyReleased
        try{
            rs=null;
            pstmt=MyLogin.con.prepareStatement("select * from STAFF_DETAIL_TABLE where ID = ?");
            pstmt.setString(1, idTextField.getText().trim());
            rs=pstmt.executeQuery();
            pstmt.clearParameters();
            if(rs.next()){                
                setData();
                BufferedImage originalImg=ImageIO.read(new File(".\\test\\Teacher_Images\\"+rs.getString("ID")+""+".jpg"));    // to read image do this
                        ImageIcon icon=new ImageIcon(ImageProcessing.myResize(originalImg,imgLabel.getWidth(),imgLabel.getHeight()));
                        imgLabel.setIcon(icon);
            }else{
                imgLabel.setIcon(null);
                clearFields();
            }
        }catch(Exception e){
            System.out.println("Problem inside id "+e);
        }
    }//GEN-LAST:event_idTextFieldKeyReleased

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));    
        String id="",name="",fname="",dob="",gender="",mobno="",hphone="",qualification="",tenth="",twelth="",ug="",pg="",joindt="",resigndt="",desc="",add="";
            int flag=0;
            DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
        try{    
            rs=null;
            id=idTextField.getText().trim();
            pstmt=MyLogin.con.prepareStatement("select * from STAFF_DETAIL_TABLE where ID=?");            
            pstmt.setString(1, id);
            rs=pstmt.executeQuery();
            pstmt.clearParameters();
            if(rs.next()){
                    name=nameTextField.getText().trim();
                    fname=fnameTextField.getText().trim();
                    try{
                        dob=df.format(dobDateChooser.getDate());
                    }catch(Exception e){  }                                            
                    gender=(String)genderComboBox.getSelectedItem();
                    mobno=mobnoTextField.getText().trim();
                    hphone=hphoneTextField.getText().trim();
                    qualification=(String)qualificationComboBox.getSelectedItem();
                    tenth=tenthTextField.getText().trim();
                    twelth=twelthTextField.getText().trim();
                    ug=ugTextField.getText().trim();
                    pg=pgTextField.getText().trim();
                    try{
                        joindt=df.format(joinDateChooser.getDate());
                    }catch(Exception e){  }
                    try{
                        resigndt=df.format(resignDateChooser.getDate());
                    }catch(Exception e){  }
                    desc=(String)descComboBox.getSelectedItem();
                    add=addTextArea.getText();
                                                               
                            if((name.equalsIgnoreCase(rs.getString("FULL_NAME"))||name.equals(""))==false){
                                flag=myUpdate("FULL_NAME",name,id);  // flag is to give msg of success
                            }
                            if(((fname.equalsIgnoreCase(rs.getString("FATHER_NAME")))||fname.equals(""))==false){   
                                flag=myUpdate("FATHER_NAME",fname,id);
                            }
                            if((dob.equalsIgnoreCase(rs.getString("DOB"))||dob.length()!=11)==false){
                                flag=myUpdate("DOB",dob,id);
                            }
                            if(((gender.equalsIgnoreCase(rs.getString("GENDER")))||gender.equalsIgnoreCase("---Select---"))==false) {
                                flag=myUpdate("GENDER",gender,id);
                            }
                            if((mobno.equalsIgnoreCase(rs.getString("MOB_NO"))||mobno.equals("")||mobno.length()!=10)==false){
                                flag=myUpdate("MOB_NO",mobno,id);
                            }
                            if((hphone.equalsIgnoreCase(rs.getString("H_PHONE"))||hphone.equals("")||hphone.length()!=10)==false){
                                flag=myUpdate("H_PHONE",hphone,id);
                            }
                            if(((qualification.equalsIgnoreCase(rs.getString("QUALIFICATION")))||qualification.equalsIgnoreCase("---Select---"))==false) {
                                flag=myUpdate("QUALIFICATION",qualification,id);
                            }
                            if((tenth.equalsIgnoreCase(rs.getString("TENTH"))||tenth.equals("")||tenth.length()>5||tenth.length()==1)==false){
                                flag=myUpdate("TENTH",tenth,id);
                            }
                            if((twelth.equalsIgnoreCase(rs.getString("TWELTH"))||twelth.length()>5||twelth.length()==1)==false){
                                flag=myUpdate("TWELTH",twelth,id);
                            }
                            if((ug.equalsIgnoreCase(rs.getString("UG"))||ug.length()>5||ug.length()==1)==false){
                                flag=myUpdate("UG",ug,id);
                            }
                            if((pg.equalsIgnoreCase(rs.getString("PG"))||pg.length()>5||pg.length()==1)==false){
                                flag=myUpdate("PG",pg,id);
                            }
                            if((joindt.equalsIgnoreCase(rs.getString("JOIN_DATE"))||joindt.length()!=11)==false){
                                flag=myUpdate("JOIN_DATE",joindt,id);
                            }
                            if((resigndt.equalsIgnoreCase(rs.getString("RESIGN_DATE"))||resigndt.length()!=11)==false){
                                flag=myUpdate("RESIGN_DATE",resigndt,id);
                            }
                            if(((desc.equalsIgnoreCase(rs.getString("POSITION")))||desc.equalsIgnoreCase("---Select---"))==false) {
                                flag=myUpdate("POSITION",desc,id);
                            }
                            if((add.equalsIgnoreCase(rs.getString("ADDRESS"))||add.equals(""))==false){
                                System.out.println("before method call of address flag = "+flag);
                                flag=myUpdate("ADDRESS",add,id);  // flag is to give msg of success
                                System.out.println("After method call of address flag = "+flag);
                            }
            }
            if(flag==1){     
                pstmt=MyLogin.con.prepareStatement("select * from STAFF_DETAIL_TABLE where ID = '"+id+"'");
                rs=pstmt.executeQuery();
                if(rs.next()){
                    setData();
                    JOptionPane.showMessageDialog(null, "One Record Modified Successfully", "Modify Detail", JOptionPane.INFORMATION_MESSAGE);                
                }
            }else{
                JOptionPane.showMessageDialog(null, "No changes made","Modify Detail",JOptionPane.PLAIN_MESSAGE);
            }            
        }catch(Exception e){
            System.out.println("Problem inside modify "+e);
        }
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR)); 
        String id="";
         id=idTextField.getText();
    try{    
        if(id.equalsIgnoreCase(rs.getString("ID"))){
            int i=JOptionPane.showConfirmDialog(null, "Are you sure you want to permanently delete this record", "Delete Record", JOptionPane.CANCEL_OPTION);
            if(i==0){                       
                    pstmt=MyLogin.con.prepareStatement("delete from STAFF_DETAIL_TABLE where ID = ?");
                    pstmt.setString(1, id);
                    int j=pstmt.executeUpdate();
                    pstmt.clearParameters();
                    if(j>0){
                        
                        File file1 = new File(".\\test\\Teacher_Images\\"+id+".jpg");                   
                        if(file1.delete()) { 
                            imgLabel.setIcon(null);
                            System.out.println(file1.getName() + " is deleted!");
                        } else {
                             System.out.println("Delete operation is failed.");
                          }                       
                        JOptionPane.showMessageDialog(null, "One Record Delete Successfully", "Delete", JOptionPane.INFORMATION_MESSAGE);
                        rs=null;
                        idTextField.setText("");
                        clearFields();
                    }  
                    System.out.println("record cannot be deleted");
            }
        }else{            
            JOptionPane.showMessageDialog(null, "Invalid Id, Detail cannot be deleted","Delete",JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
                    System.out.println("Problem inside delete button"+e);
                }
    deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void imgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLabelMouseClicked
        imgLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try
        {
            JFileChooser chooser=new JFileChooser();
            chooser.setCurrentDirectory(new File("."));     // seting current directory
                       // or
        //      chooser.setCurrentDirectory(new File("desktop"));
            int result = chooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION)
            {
                String file_address =chooser.getSelectedFile().getPath();
                file=new File(file_address);

                if((ImageIO.read(file)==null)) // file type
                    JOptionPane.showMessageDialog(null,"Please select .jpg file only");
                else
                {
                    BufferedImage originalimg=ImageIO.read(file);
                    ImageIcon icon=new ImageIcon(ImageProcessing.myResize(originalimg,imgLabel.getWidth(),imgLabel.getHeight()));
                    imgLabel.setIcon(icon);
                }
            }
            else
            JOptionPane.showMessageDialog(null,"Please Select file");
        }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
        imgLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));   
    }//GEN-LAST:event_imgLabelMouseClicked

    /**
     * @param evt*   
     * @param letters**************************************************************************************/   
    public void checkLetters(java.awt.event.KeyEvent evt,String letters){
        char cr=evt.getKeyChar();
        if(!((Character.isLetter(cr))||(cr==KeyEvent.VK_BACKSPACE)||(cr==KeyEvent.VK_SPACE))){
            getToolkit().beep();
            evt.consume();
        }
        if(letters.length()>49){
                getToolkit().beep();
                evt.consume();                  
        }
    }   
    
    /**
     * @param evt*
     * @param fieldname**************************************************************************************/
    public void checkNumbers(java.awt.event.KeyEvent evt,javax.swing.JTextField fieldname){
        char cr=evt.getKeyChar();
        if(!(Character.isDigit(cr) || (cr==KeyEvent.VK_BACKSPACE)||cr==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
        if(fieldname.getText().length()>9){
            getToolkit().beep();
            evt.consume();                   
        }
    }
    
    /**
     * @param evt*
     * @param fieldname*************************************************************************************/
    public void checkForPercentage(java.awt.event.KeyEvent evt,javax.swing.JTextField fieldname){
        char cr=evt.getKeyChar();
        System.out.println(""+cr);
        if(!(Character.isDigit(cr)||((int)cr==46)||cr==KeyEvent.VK_BACKSPACE)){
            getToolkit().beep();
            evt.consume();
        }
        if(fieldname.getText().length()>4){
            getToolkit().beep();
            evt.consume();
        }
    } 
    
    private void nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyTyped
        checkLetters(evt, nameTextField.getText());
    }//GEN-LAST:event_nameTextFieldKeyTyped

    private void fnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameTextFieldKeyTyped
        checkLetters(evt, fnameTextField.getText());
    }//GEN-LAST:event_fnameTextFieldKeyTyped
      
    private void mobnoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobnoTextFieldKeyTyped
        checkNumbers(evt, mobnoTextField);
    }//GEN-LAST:event_mobnoTextFieldKeyTyped

    private void hphoneTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hphoneTextFieldKeyTyped
        checkNumbers(evt, hphoneTextField);
    }//GEN-LAST:event_hphoneTextFieldKeyTyped

    private void tenthTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenthTextFieldKeyTyped
        checkForPercentage(evt, tenthTextField);
    }//GEN-LAST:event_tenthTextFieldKeyTyped

    private void twelthTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_twelthTextFieldKeyTyped
        checkForPercentage(evt, twelthTextField);
    }//GEN-LAST:event_twelthTextFieldKeyTyped

    private void ugTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ugTextFieldKeyTyped
        checkForPercentage(evt, ugTextField);
    }//GEN-LAST:event_ugTextFieldKeyTyped

    private void pgTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pgTextFieldKeyTyped
        checkForPercentage(evt, pgTextField);
    }//GEN-LAST:event_pgTextFieldKeyTyped

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        MainPage ob = new MainPage();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backLabelMouseClicked

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        // TODO add your handling code here:
        refreshLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        StaffDetail ob = new StaffDetail();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_refreshLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try{
            MyLogin.con.close();
        }catch(Exception e){ }

        MyLogin ob=new MyLogin();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private com.toedter.calendar.JYearChooser YearChooser;
    private javax.swing.JTextArea addTextArea;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> descComboBox;
    private javax.swing.JTextField descTextField;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JTextField hphoneTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser joinDateChooser;
    private javax.swing.JTextField joinTextField;
    private javax.swing.JLabel joindateLabel;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTextField mobnoTextField;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField pgTextField;
    private javax.swing.JComboBox<String> qualificationComboBox;
    private javax.swing.JTextField qualificationTextField;
    private javax.swing.JLabel refreshLabel;
    private com.toedter.calendar.JDateChooser resignDateChooser;
    private javax.swing.JTextField resignTextField;
    private javax.swing.JLabel resigndateLabel;
    private javax.swing.JTextField tenthTextField;
    private javax.swing.JLabel totLabel1;
    private javax.swing.JLabel totLabel2;
    private javax.swing.JTextField twelthTextField;
    private javax.swing.JTextField ugTextField;
    // End of variables declaration//GEN-END:variables
}
